language: node_js
sudo: false
node_js:
  - "4"
  - "6"
before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - npm i -g npm
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "iPIfBSDAW73riwJOdKYUU2ztPE6lbsrldFQsf2ywYyrbjWed74jDxsT+WdrYmnvBEMd9A81/c3HDg7Hrhhk5d8G4+2CvPDoucN1GzNji642DmlExs0L9yMy3ONsDOFgprWQNLCcqgEFBLhlbuFlFZfsWs/jVQIiUjWLgQJzZCnA="
    on:
      tags: true
      node_js: "6"
